[2022-10-25T01:34:47.525+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: enriched_data_aggregations.load_and_generate_aggregations manual__2022-10-25T01:34:43.427609+00:00 [queued]>
[2022-10-25T01:34:47.593+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: enriched_data_aggregations.load_and_generate_aggregations manual__2022-10-25T01:34:43.427609+00:00 [queued]>
[2022-10-25T01:34:47.610+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-25T01:34:47.616+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-25T01:34:47.631+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-25T01:34:47.806+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_and_generate_aggregations> on 2022-10-25 01:34:43.427609+00:00
[2022-10-25T01:34:47.832+0000] {standard_task_runner.py:54} INFO - Started process 11944 to run task
[2022-10-25T01:34:47.881+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'enriched_data_aggregations', 'load_and_generate_aggregations', 'manual__2022-10-25T01:34:43.427609+00:00', '--job-id', '587', '--raw', '--subdir', 'DAGS_FOLDER/data_agg.py', '--cfg-path', '/tmp/tmp7j4_d8og']
[2022-10-25T01:34:47.929+0000] {standard_task_runner.py:83} INFO - Job 587: Subtask load_and_generate_aggregations
[2022-10-25T01:34:48.235+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_agg.py
[2022-10-25T01:34:49.167+0000] {task_command.py:384} INFO - Running <TaskInstance: enriched_data_aggregations.load_and_generate_aggregations manual__2022-10-25T01:34:43.427609+00:00 [running]> on host 0c46e38e1c8e
[2022-10-25T01:34:50.075+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=enriched_data_aggregations
AIRFLOW_CTX_TASK_ID=load_and_generate_aggregations
AIRFLOW_CTX_EXECUTION_DATE=2022-10-25T01:34:43.427609+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-25T01:34:43.427609+00:00
[2022-10-25T01:35:19.476+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pyspark_scripts.py", line 273, in load_and_aggregate
    temporal_df = spark.read.option('header', 'true').parquet(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 364, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/airflow/opt/airflow/dags/storage/enriched_data
[2022-10-25T01:35:19.567+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=enriched_data_aggregations, task_id=load_and_generate_aggregations, execution_date=20221025T013443, start_date=20221025T013447, end_date=20221025T013519
[2022-10-25T01:35:19.647+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 587 for task load_and_generate_aggregations (Path does not exist: file:/opt/airflow/opt/airflow/dags/storage/enriched_data; 11944)
[2022-10-25T01:35:19.730+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-25T01:35:19.882+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
